# STAC Connection information
[stac]
catalog_url = "https://explorer.digitalearth.africa/stac"

[stac.rio_config]
cloud_defaults = true
aws = { aws_unsigned = true }
AWS_S3_ENDPOINT = "s3.af-south-1.amazonaws.com"

[stac.configured_products]
"Sentinel 2" = "s2_l2a"

# Sentinel-2 Product Definition
[s2_l2a]

[s2_l2a.pixel_quality_mask]
band = "SCL"
type = "categorical"
categories_to_mask = ["cloud high probability", "cloud medium probability", "thin cirrus", "cloud shadows", "saturated or defective"]

[s2_l2a.mask.flags_definition]
bits = [0, 1, 2, 3, 4, 5, 6, 7]

[s2_l2a.mask.flags_definition.values]
"no data" = 0
"saturated or defective" = 1
"dark area pixels" = 2
"cloud shadows" = 3
"vegetation" = 4
"bare soils" = 5
"water" = 6
"unclassified" = 7
"cloud medium probability" = 8
"cloud high probability" = 9
"thin cirrus" = 10
"snow or ice" = 11

[s2_l2a.assets."*"]
data_type = "uint16"
nodata = 0
unit = "1"

[s2_l2a.assets.SCL]
data_type = "uint8"
nodata = 0
unit = "1"

[s2_l2a.aliases]
costal_aerosol = "B01"
blue = "B02"
green = "B03"
red = "B04"
red_edge_1 = "B05"
red_edge_2 = "B06"
red_edge_3 = "B07"
nir = "B08"
nir_narrow = "B08A"
water_vapour = "B09"
swir_1 = "B11"
swir_2 = "B12"
mask = "SCL"
aerosol_optical_thickness = "AOT"
scene_average_water_vapour = "WVP"



