name: remotesensingtools
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.9.19
  - pip
  # Formatting and Linters
  - black
  - mypy
  - pylint
  # Jupyter Notebooks
  - ipykernel
  - ipython
  # Utilities
  - click
  - tqdm
  # Spatial
  - fiona
  - geopandas # this will include gdal through conda-forge
  - shapely
  - rasterio
  - xarray
  # Data Science
  - matplotlib
  - numpy
  - pandas
  # Project-Specific Packages 
  - pystac-client
  - odc-stac
  - odc-geo