name: frontiersibase
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.7.12
  - pip=24.0
  # Formatting and Linters
  - black=24.2.0
  - mypy=1.9.0
  - pylint=3.1.0
  # Jupyter Notebooks
  - ipykernel=6.29.3
  - ipython=8.22.2
  # Utilities
  - click=8.1.7
  - tqdm=4.66.2
  # Data Science
  - geopandas=0.14.3
  - matplotlib=3.8.3
  - numpy=1.26.4
  - pandas=2.2.1
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  # Project-Specific Packages 