# STAC Connection information
[stac]
catalog_url = "https://explorer.sandbox.dea.ga.gov.au/stac"

[stac.rio_config]
cloud_defaults = true
aws = { aws_unsigned = true }
AWS_S3_ENDPOINT = "s3.ap-southeast-2.amazonaws.com"

[stac.configured_products]
"Sentinel 2a" = "ga_s2am_ard_3"
"Sentinel 2b" = "ga_s2bm_ard_3"

# Sentinel-2a Product Definition
[ga_s2am_ard_3]

[ga_s2am_ard_3.pq_mask]
band = "oa_fmask"
type = "categorical"
categories_to_mask = ["cloud", "shadow", "snow", "water"]

[ga_s2am_ard_3.pq_mask.flags_definition]
bits = [0, 1, 2, 3, 4, 5, 6, 7]

[ga_s2am_ard_3.pq_mask.flags_definition.values]
"no data" = 0
"valid" = 1
"cloud" = 2
"shadow" = 3
"snow" = 4
"water" = 5

[ga_s2am_ard_3.assets."*"]
data_type = "int16"
nodata = -999
unit = "1"

[ga_s2am_ard_3.assets.oa_fmask]
data_type = "uint8"
nodata = 0
unit = "1"

[ga_s2am_ard_3.aliases]
costal_aerosol = "nbart_coastal_aerosol"
blue = "nbart_blue"
green = "nbart_green"
red = "nbart_red"
red_edge_1 = "nbart_red_edge_1"
red_edge_2 = "nbart_red_edge_2"
red_edge_3 = "nbart_red_edge_3"
nir = "nbart_nir_1"
nir_narrow = "nbart_nir_2"
swir_1 = "nbart_swir_2"
swir_2 = "nbart_swir_3"
pq_mask = "oa_fmask"

# Sentinel-2b Product Definition
[ga_s2bm_ard_3]

[ga_s2bm_ard_3.pq_mask]
band = "oa_fmask"
type = "categorical"
categories_to_mask = ["cloud", "shadow", "snow", "water"]

[ga_s2bm_ard_3.pq_mask.flags_definition]
bits = [0, 1, 2, 3, 4, 5, 6, 7]

[ga_s2bm_ard_3.pq_mask.flags_definition.values]
"no data" = 0
"valid" = 1
"cloud" = 2
"shadow" = 3
"snow" = 4
"water" = 5

[ga_s2bm_ard_3.assets."*"]
data_type = "uint16"
nodata = -999
unit = "1"

[ga_s2bm_ard_3.assets.oa_fmask]
data_type = "uint8"
nodata = 0
unit = "1"

[ga_s2bm_ard_3.aliases]
costal_aerosol = "nbart_coastal_aerosol"
blue = "nbart_blue"
green = "nbart_green"
red = "	nbart_red"
red_edge_1 = "nbart_red_edge_1"
red_edge_2 = "nbart_red_edge_2"
red_edge_3 = "nbart_red_edge_3"
nir = "nbart_nir_1"
nir_narrow = "nbart_nir_2"
swir_1 = "nbart_swir_2"
swir_2 = "nbart_swir_3"
pq_mask = "oa_fmask"