# STAC Connection information
[catalog]
name = "Digital Earth Australia"
url = "https://explorer.sandbox.dea.ga.gov.au/stac"

[catalog.rio_config]
cloud_defaults = true
aws = { aws_unsigned = true }
AWS_S3_ENDPOINT = "s3.ap-southeast-2.amazonaws.com"

# Sentinel-2a Product Definition
[collections.ga_s2am_ard_3]
description = "Sentinel-2a"

# band aliases 
[collections.ga_s2am_ard_3.aliases]
costal_aerosol = "nbart_coastal_aerosol"
blue = "nbart_blue"
green = "nbart_green"
red = "nbart_red"
red_edge_1 = "nbart_red_edge_1"
red_edge_2 = "nbart_red_edge_2"
red_edge_3 = "nbart_red_edge_3"
nir = "nbart_nir_1"
nir_narrow = "nbart_nir_2"
swir_1 = "nbart_swir_2"
swir_2 = "nbart_swir_3"
fmask = "oa_fmask"

# List default metadata attributes for all assets
[collections.ga_s2am_ard_3.assets."*"]
data_type = "int16"
nodata = -999
unit = "1"

# Overwrite metadata for SCL
[collections.ga_s2am_ard_3.assets.oa_fmask]
data_type = "uint8"
nodata = 0
unit = "1"

# Set up all ga_s2am_ard_3 masks
[collections.ga_s2am_ard_3.masks]

# Set up oa_fmask config
[collections.ga_s2am_ard_3.masks.oa_fmask]
alias = "fmask"
description = "Function of mask"
type = "categorical"
categories_to_mask = ["cloud", "shadow", "snow", "water"]
flags_definition.bits = [0, 1, 2, 3, 4, 5, 6, 7]

[collections.ga_s2am_ard_3.masks.oa_fmask.flags_definition.values]
"no data" = 0
"valid" = 1
"cloud" = 2
"shadow" = 3
"snow" = 4
"water" = 5

# Sentinel-2b Product Definition
[collections.ga_s2bm_ard_3]
description = "Sentinel-2b"

# Band aliases
[collections.ga_s2bm_ard_3.aliases]
costal_aerosol = "nbart_coastal_aerosol"
blue = "nbart_blue"
green = "nbart_green"
red = "nbart_red"
red_edge_1 = "nbart_red_edge_1"
red_edge_2 = "nbart_red_edge_2"
red_edge_3 = "nbart_red_edge_3"
nir = "nbart_nir_1"
nir_narrow = "nbart_nir_2"
swir_1 = "nbart_swir_2"
swir_2 = "nbart_swir_3"
fmask = "oa_fmask"

# List default metadata attributes for all assets 
[collections.ga_s2bm_ard_3.assets."*"]
data_type = "int16"
nodata = -999
unit = "1"

# Overwrite metadata for oa_fmask
[collections.ga_s2bm_ard_3.assets.oa_fmask]
data_type = "uint8"
nodata = 0
unit = "1"

# Set up oa_fmask
[collections.ga_s2bm_ard_3.masks]

# Set up oa_fmask config
[collections.ga_s2bm_ard_3.masks.oa_fmask]
alias = "fmask"
description = "Function of mask"
type = "categorical"
categories_to_mask = ["cloud", "shadow", "snow", "water"]
flags_definition.bits = [0, 1, 2, 3, 4, 5, 6, 7]

[collections.ga_s2bm_ard_3.masks.oa_fmask.flags_definition.values]
"no data" = 0
"valid" = 1
"cloud" = 2
"shadow" = 3
"snow" = 4
"water" = 5